# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run Data Creator

on:
  schedule:
  - cron: '0 17,19,21,23,1 * * *'
  workflow_dispatch:
  
jobs:
  run-data-creator:
    run-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv ratelimit

    - name: Run dataCreator.py
      env:
        API_KEY: ${{ screts.API_KEY}}
      run: |
        python dataCreator.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add leaderboard_data.json
        git commit -m 'Update leaderboard data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
