name: Run Data Creator

on:
  schedule:
    - cron: '0 19-23 * * *' # every day from 19:00 to 23:00
    - cron: '0 0-3 * * *'   # every day from 00:00 to 03:00
  workflow_dispatch:

jobs:
  run-data-creator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv ratelimit

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes
      run: |
        git pull origin main  # Adjust 'main' to your default branch if necessary

    - name: Run dataCreator.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python dataCreator.py

    - name: Commit and push changes
      run: |
        git add leaderboard_data.json
        git commit -m 'Update leaderboard data' || echo "No changes to commit"
        git push origin main  # Adjust 'main' if your default branch has a different name
