name: Player Locker

on:
  schedule:
    # Main elim (3 times)
    - cron: '0 5 30,31 * *'  # Runs at 5:00 AM on the 30th and 31st of every month
    - cron: '0 5 1-6 * *'    # Runs at 5:00 AM on the 1st to 6th of every month
    # Top 3 elim (1 time)
    - cron: '0 5 7-8 4 *'    # Runs at 5:00 AM on the 7th and 8th of April
  workflow_dispatch:

jobs:
  run-data-creator:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes
      run: |
        git pull origin main  # Adjust 'main' to your default branch if necessary

    # Main Elim (Run 1)
    - name: Run playerLocker.py (Main Elim - Run 1)
      if: github.event.schedule == '0 5 30,31 * *' || github.event.schedule == '0 5 1-6 * *'
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python playerLocker.py

    # Main Elim (Run 2)
    - name: Run playerLocker.py (Main Elim - Run 2)
      if: github.event.schedule == '0 5 30,31 * *' || github.event.schedule == '0 5 1-6 * *'
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python playerLocker.py

    # Main Elim (Run 3)
    - name: Run playerLocker.py (Main Elim - Run 3)
      if: github.event.schedule == '0 5 30,31 * *' || github.event.schedule == '0 5 1-6 * *'
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python playerLocker.py

    # Top 3 Elim
    - name: Run playerLocker.py (Top 3 Run)
      if: github.event.schedule == '0 5 7-8 4 *'
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python playerLocker.py

    # TEST
    - name: Run playerLocker.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        python playerLocker.py

    - name: Commit and push changes
      run: |
        git add player_ID.json
        git commit -m 'Update PlayerID data' || echo "No changes to commit"
        git push origin main  # Adjust 'main' if your default branch has a different name